### PR TITLE
feat(benches): Add req/rep socket throughput benchmarks

### PR DESCRIPTION
**Pull request by PatStiles**
Addresses #6 . I added a benchmark for 2 req sockets contending with against the same rep socket. Appreciate any feedback on timing it more precisely.

### CODE REVIEW

**Comment by jonasbostoen** [comment]
Hi, this currently doesn't compile due to some typos. Apart from that it looks good!

**Comment by PatStiles** [comment]
rip this is what you get for submitting pr's late at night...

**Comment by PatStiles** [comment]
@jonasbostoen refactored!
Screenshot 2023-10-20 at 09 32 21

**Comment by jonasbostoen** [comment]
Looks good @PatStiles! I think you still need to push the last commit?

**Pull request closed without merging**
